import { Inter } from "next/font/google";
import "../globals.css";
import Nav from "@/components/root/nav";
import Footer from "@/components/root/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Nav />
      {children}
      <Footer />
    </>
  );
}
