import Nav from "@/components/root/nav";
import Footer from "@/components/root/footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="overflow-x-hidden">
      <Nav />
      {children}
      <Footer />
    </div>
  );
}
